# Generated by Django 4.0.4 on 2022-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
